### PR TITLE
Add support for golang package

### PR DESCRIPTION
**Pull request by olavphibm**

### CODE REVIEW

**Comment by olavphibm** [comment]
test_plz

**Comment by olavphibm** [comment]
test_plz

**Comment by olavphibm** [comment]
test_plz

**Comment by maurorodrigues** [comment]
looks like #40 already contains this commits, can we close this PR @olavphibm ?

**Comment by olavphibm** [comment]
@maurorodrigues Either we merge this first and leave only the docker commits for #40 or we merge everything at once on #40. So, yes, we can close this.

**Pull request merged**
