### PR TITLE
Make centos case in package (yaml) metadata files consistent with the one used in the rest of the code

### PR DESCRIPTION
**Pull request by alanoe**
… one used in the rest of the code

### CODE REVIEW

**Comment by olavphibm** [comment]
start build

**Comment by mopsfelder** [comment]
`centos` is fine, if we adopt a lower case in directory names and in yaml file references.

If we prefer to use camel case to refer to CentOS, as the distro or as the project, I think we should follow its real name, `CentOS` - with capital `C` and capital `OS`.

`centOS` stays in between of not being completely lower case and not entirely correct.

What do you think?

**Comment by alanoe** [comment]
I don't care about the case, as long as it is consistent. Switching from centOS to CentOS

**Comment by olavphibm** [comment]
start build

**Pull request merged**
