### PR TITLE
open-power-host-os metapackage: replace '.el7.centos' with '%{dist}'.

### PR DESCRIPTION
**Pull request by cuinutanix**
For open-power-host-os dependencies, replace hard-coded '.el7.centos' with %{dist}.

This allows one to change %{dist} globally for all packages on the mock command line and not break the dependencies of open-power-host-os packages.

### CODE REVIEW

**Comment by olavphibm** [comment]
We have a script (`host_os.py update-versions`) that is run periodically to update the versions of packages from the top of their branches on github. This script also updates the `open-power-host-os.spec` file accordingly, with the exact required packages NEVRA's. I will need to update this script to avoid overwriting your changes.

Just for me to better understand your use case, why do you need to change the `%{dist}` macro?

**Comment by olavphibm** [comment]
start tests

**Comment by cuinutanix** [comment]
I think this is the convention for %{dist}:
.el7 : unmodified from RHEL
.el7.centos : with CentOS.org modifications

Then for RPMs built by Nutanix, or that we modify, we set %{dist} to '.el7.nutanix'. This is to make it easier for our users to where the upstream RPM comes from, who made modifications, and where they should go to get SRPMs.

I also recommend that for the official open-power-host-os builds, %{dist} should be set to something other than '.el7.centos' to indicate that the package in fact did not come from CentOS.org.

**Comment by mopsfelder** [comment]
It is possible to set `%dist` tag by adding `--define "dist .mydistro"` to the mock arguments.  Mock arguments are set in `mock_args` parameter of `config.yaml` file.

Example:

```yaml
 mock_args:
   # If the system has less RAM than required, the plugin will be disabled
   "--enable-plugin=tmpfs
   --plugin-option=tmpfs:keep_mounted=True
   --plugin-option=tmpfs:max_fs_size=32g
   --plugin-option=tmpfs:required_ram_mb=39800
   --verbose
   --define 'dist .mydistro'"
```

I think we can update `host-os.py` to list dependencies in the format of `name-version-release` (without %dist tag).

@olavphibm @fabianorosas What do you think?

**Comment by olavphibm** [comment]
@cuinutanix Thanks for clarifying. This indeed feels better.
@mopsfelder I agree. I'll make the necessary modifications.

**Comment by olavphibm** [comment]
I've modified the update script to use the `%{dist}` tag too: https://github.com/open-power-host-os/builds/pull/237

**Pull request merged**
