### PR TITLE
Remove outdated packages

### PR DESCRIPTION
**Pull request by olavphibm**
Those packages' versions were caught up by CentOS and no longer need to be built by us.

### CODE REVIEW

**Comment by fabianorosas** [comment]
We also need to remove these from https://github.com/open-power-host-os/builds/blob/master/config.yaml

**Comment by olavphibm** [comment]
@fabianorosas And README.rst. Thanks for remembering.

**Comment by mopsfelder** [comment]
There is always a special detachment feeling when getting rid of old stuff.  Thank you all for this pull request!

**Comment by olavphibm** [comment]
start build

**Pull request merged**
