### PR TITLE
Add support to systemtap 3.0

### PR DESCRIPTION
**Pull request by fabianorosas**

### CODE REVIEW

**Comment by maurorodrigues** [comment]
Can one of the admins verify this patch?

**Comment by olavphibm** [comment]
test_plz

**Comment by olavphibm** [comment]
test_plz

**Comment by olavphibm** [comment]
test_plz

**Comment by olavphibm** [comment]
test_plz

**Comment by maurorodrigues** [comment]
test_plz

**Comment by maurorodrigues** [comment]
@fabianorosas Also you added a patch to make this package work with kernel 4.7, can you add a task to confirm or to ask the test team to confirm that it works with 4.8 as well?
Thanks!

**Pull request merged**
