### PR TITLE
Add libservicelog and servicelog

### PR DESCRIPTION
**Pull request by maurorodrigues**
Libservicelog:
project: open-power-host-os/libservicelog 
Branch: hostos-devel

Servicelog:
project: open-power-host-os/servicelog 
Branch: hostos-devel

Fixes and Closes open-power-host-os/builds#11

### CODE REVIEW

**Comment by maurorodrigues** [comment]
test_plz

**Comment by maurorodrigues** [comment]
test_plz

**Comment by olavphibm** [comment]
You could mention where you're getting the spec files from in the commit messages.

**Comment by maurorodrigues** [comment]
sure thing! I'll update in a minute!

**Pull request merged**
