### PR TITLE
[WIP]Skip tests (spec's %check) of docker, flannel, golang, gcc, kubernetes, libguestfs, libseccomp, libvirt.

### PR DESCRIPTION
**Pull request by maurorodrigues**
In order to use this feature we need to use the `--mock-args` feature implemented in open-power-host-os/builds#123 as follows:
```--mock-args "--define 'skiptests 0' "``` or
```--mock-args "--define 'skiptests %{nil}' "```
The value defined doesn't really matter since the test in the spec is for its definition.

For instance gcc build is almost 60% quicker (the commits messages of packages which have tests contains such information)

Note: Not all the packages got the skiptests feature since not all of the have the %check phase.

### CODE REVIEW

**Comment by fabianorosas** [comment]
Couldn't we use the `--with` and `--without` options instead of `--define`?

Doc:
http://rpm5.org/docs/api/conditionalbuilds.html

Example usage:
http://pkgs.fedoraproject.org/cgit/rpms/samba.git/plain/samba.spec
http://pkgs.fedoraproject.org/cgit/rpms/mutt.git/plain/mutt.spec

**Comment by maurorodrigues** [comment]
Does it really matter if we use --define or --with? Even more when with is a --define underneath its implementation and its usage is pretty much the same.

Personally, when I read --with or --without I immediately connect to the --with-something parameters from config to turn on features and that's the impression I have after reading the docs as well. Again personally I don't think something so tied to features enablement should be used as a mechanism to skip a spec phase (even though it already happens, see flanel.spec)

So I don't have any strong feeling both things work the same way and thus, if this is really the prefered approach I can change it in a minute, no problems at all.

**Comment by fabianorosas** [comment]
@maurorodrigues Well, there is a difference in readability, at least:
```
%if %{without tests}
--mock-args "--without tests"
```
vs.
```
%if %{?skiptests:0}
--mock-args "--define 'skiptests 0' "
```

but since you feel the 'with' is not appropriate in this context, let's keep things as they are.

**Comment by maurorodrigues** [comment]
The point here is to get things built faster, to keep the default behavior when no parameter is passed and that's achieved.

So let's use the fact it is a WIP (almost done but a WIP) to decide @olavphibm @gutoyr @mopsfelder @snowcrshd can you please help us to decide the matter here? I honestly don't have any preference and since this, soon, will not be my burden to carry I'll leave it up to you.

**Comment by olavphibm** [comment]
I agree with Fabiano that `--with` improves readability.
`"--define 'skiptests %{nil}' "` looks like it's not skipping the tests.

**Comment by snowcrshd** [comment]
@olavphibm ditto. 

Specially @fabianorosas example of the `--without tests`.
Much easier to understand what that is doing.

`--define 'skiptests 0'` automatically makes me think why do I have to use `0`.

**Comment by olavphibm** [comment]
start tests

**Comment by olavphibm** [comment]
start build

**Comment by olavphibm** [comment]
start build

**Comment by mopsfelder** [comment]
This pull request will be closed in favor of pull #88.

**Pull request closed without merging**
